apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-gke
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - env:
            - name: PORT
              value: '8080'
          image: gcr.io/robotic-tract-296012/github.com/jsr57v/helloworldgke
          imagePullPolicy: IfNotPresent
          name: hello-app
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld-gke
  namespace: default
spec:
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 50
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloworld-gke
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  name: hello
  namespace: default
spec:
  clusterIP: 10.3.250.140
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32729
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello
  sessionAffinity: None
  type: LoadBalancer
